serviceAccount:
  create: true
  name: argo-sa
rbac:
  - apiGroups:
    - argoproj.io
    resources:
    - applications
    verbs:
    - get
    - list
    - watch
server:
  service:
    type: LoadBalancer
