---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-application-controller-use-pod-security-policy
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
roleRef:
  kind: Role
  name: helm-use-pod-security-policy-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-server-use-pod-security-policy
subjects:
- kind: ServiceAccount
  name: argocd-server
roleRef:
  kind: Role
  name: helm-use-pod-security-policy-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-dex-server-use-pod-security-policy
subjects:
- kind: ServiceAccount
  name: argocd-dex-server
roleRef:
  kind: Role
  name: helm-use-pod-security-policy-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-sa-use-pod-security-policy
subjects:
- kind: ServiceAccount
  name: argo-sa
roleRef:
  kind: Role
  name: helm-use-pod-security-policy-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-use-pod-security-policy
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: helm-use-pod-security-policy-role
  apiGroup: rbac.authorization.k8s.io
